### PR TITLE
Implemented transform-regexp-constructors plugin

### PR DESCRIPTION
**Pull request by shinew**
Changes RegExp constructors to literals.

### CODE REVIEW

**Comment by shinew** [comment]
Updated. Also, for RegExp constructors with 0 arguments, this would currently throw at `const pattern = evals[0].value;`. Catching this case at pseudo-compile time is not terrible, but should this behavior be changed/documented?

**Comment by kangax** [comment]
Yeah, let's definitely add a check for 0 arguments. It should transform to `/(?:)/` (empty non-capturing group). Also, I would rename `evals` to `evaluatedArgs` for clarity.

**Comment by shinew** [comment]
Updated to gracefully handle empty RegExp constructions.

**Comment by kangax** [comment]
Thanks!

**Comment by kangax** [comment]
@hzoo @loganfsmyth @danez do we want to also update babili preset?

**Comment by hzoo** [comment]
yeah if want to add it now - we'll need the package.json for this package + adding it to the preset package.json if we do

**Comment by kangax** [comment]
@shinew Let's do it. That way we could also see the impact of this plugin on performance with our benchmark.

**Pull request merged**
