### PR TITLE
update benchmarks for v0.0.8 [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**
cc @iamdustan

A litte bit smaller

### CODE REVIEW

**Comment by boopathi** [comment]
we need to find a way to update benchmarks on same hardware - run on CI server - probably not going to be same configuration container every time I suppose. How do projects generally run benchmarks ?

**Comment by hzoo** [comment]
Oh another thing we can do is run a diff of the outputs

**Comment by kangax** [comment]
We should definitely do a diff. That's what React does — compares local changes to master branch. As far as absolute numbers in readme I think it doesn't really matter. What matters is how they are in relation to gcc/uglify.

**Comment by hzoo** [comment]
Oh yeah I think I saw an example of that before but forgot cc @zpao?

**Comment by zpao** [comment]
We've not been running benchmarks per se but tallying some data so we can compare runs (I think we did some perf stuff in the past but weren't getting a ton of great data). For the tallying, we just update a text file as a lazy DB in a branch from CI, which lets us build http://isfiberreadyyet.com/. It's pretty boring actually :)

https://github.com/facebook/react/blob/master/.travis.yml#L86-L95
https://github.com/facebook/react/blob/master/scripts/facts-tracker/index.js
https://github.com/facebook/react/blob/facts/fiber-tests.txt

**Comment by iamdustan** [comment]
that was fast!

**Comment by kangax** [comment]
How are we so behind on jQuery comparing to uglify?! This looks very fishy.

**Comment by hzoo** [comment]
Yeah we could also just run it without whitespace removal and do a diff if that can give us anything?

**Pull request merged**
