### PR TITLE
enhansed live example link

### PR DESCRIPTION
**Pull request by tomByrer**
Before, the `[] Minify (Babili)` checkbox wasn't checked.  Now it is, & includes the example code below.

### CODE REVIEW

**Comment by tomByrer** [comment]
I suggest to wait for https://github.com/babel/babel.github.io/issues/917 to be fixed first.

**Comment by hzoo** [comment]
I think you were getting the confusion from before because I didn't want to add example code but I guess we should.

**Comment by tomByrer** [comment]
Thanks, yes I needed a more 'idiot proof' example :)

**Comment by hzoo** [comment]
kk makes sense, I'm sure it was confusing to others as well

**Pull request merged**
