### PR TITLE
Don't transform String(x) to x + ''

### PR DESCRIPTION
**Pull request by boopathi**
#112

### CODE REVIEW

**Comment by hzoo** [comment]
Should we just remove it or comment? I guess someone might think to add it again

**Comment by boopathi** [comment]
I'm good for removing it. Thought it might be necessary to add some pattern that could be transformed later - and this would unbreak things that break

**Comment by boopathi** [comment]
What about adding a comment about issue and removing the code ?

**Comment by hzoo** [comment]
Cool 👍

**Comment by kangax** [comment]
This should just be part of unsafe transform, which is what UglifyJS does. 99% of the time, it's used to convert number to string so we need to give people an option to use it so long as they're aware of consequences (which we should leave in notes). It also probably should be an opt-in, similar to GCC's advanced mode.

**Comment by boopathi** [comment]
Hmm. Makes sense. I'm worried about people using Symbols - and I think it is used more and more now. Is there a way they can apply this transform without breaking symbols ? ... 

Like I want to apply the unsafe transformations (includes other type constructor transformations etc...) to most parts of the code except these places where I use `String(symbol)` - some hacky way at least ? and that I don't want to bail out completely from all the unsafe transformations because this one thing will break. I understand this argument stands for any unsafe transformation. But just want to know and document it if there is a way.

**Comment by kangax** [comment]
Do we need options for plugins then? Could be something like `simplify-builtins: true | ["symbols", ...]`

**Comment by boopathi** [comment]
Yeah. We could do something like - `includes` and `excludes` - 

with default `includes = ["bool", "array", "object", "number", "string"]` and `excludes = []`;
and excludes overrides includes, and users can specify what transformations they want to apply .. maybe ?

**Comment by kangax** [comment]
Or make it a little friendlier and provide 3 options — all, exceptSymbols, none (as an example)

**Comment by boopathi** [comment]
Oh... But we don't handle Symbol type at all ...

**Comment by kangax** [comment]
@boopathi let's rebase this too? Also this isn't documented yet, right?

**Pull request merged**
