### PR TITLE
[WIP] Simplify Tests

### PR DESCRIPTION
**Pull request by boopathi**
#76

just wrote some codemod - and hand edited some edge cases. 
https://gist.github.com/boopathi/d979e5266df861052783acf9d3e61d22

Take a look before we apply to other packages

### CODE REVIEW

**Comment by kangax** [comment]
My concern is that source and destination strings are in different places so it might be annoying to look back and forth.

@hzoo what do ya think

**Comment by boopathi** [comment]
Yeah, I felt that too. So I thought we could do

```
expect({
  source,
  result: transform(source)
}).toMatchSnapshot()
```

**Comment by hzoo** [comment]
A good point - being able to see the source/expected easily is useful

**Comment by kangax** [comment]
Not sure if snapshot is the most appropriate approach here unless we can have input/output specified together.

**Comment by hzoo** [comment]
Maybe we can leave this here and revisit.

Implementing what I wrote originally is easier and just reduces boilerplate

**Pull request closed without merging**
