### PR TITLE
Fix removal of quotes from property names

### LINKED ISSUE #415: Syntax errors after minifying unicode
Trying to use [mathiasbynens/he](https://github.com/mathiasbynens/he) to encode html entities in the browser, but after adding the library, the app has started getting syntax errors in Safari and Firefox.

The offending character seems to be a unicode character, that appears in the source after minification.

Here's the result of running the corresponding snippet of code in [Babel's REPL with Babili enabled](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&code=let%20a%20%3D%20%7B%20'%5Cu2118'%3A'wp'%20%7D&experimental=false&loose=false&spec=false&playground=false):

```js
let a = { '\u2118':'wp' };
// becomes
'use strict';var a={℘:'wp'};
```

Visiting that link in Firefox 50.1.0 results in an "Illegal character error" in the REPL. Seeing as it works fine without Babili, I'm guessing this is a bug, rather than a deliberate constraint.

Pretty sure it happens in [babel-plugin-transform-property-literals](https://github.com/babel/babili/tree/master/packages/babel-plugin-transform-property-literals) as it turns the string into a literal key.

### PR DESCRIPTION
**Pull request by boopathi**
+ Fix #416 
+ Fix #445 
+ Fix #415

### CODE REVIEW

**Comment by boopathi** [comment]
@mathiasbynens Would like you to review this. There are a few more corner cases missing I suppose - for example - `.123`. But, is there a esutils API like - `isPropertyNameES5` like `isIdentifierES5` ?

**Comment by boopathi** [comment]
Or would it suffice to only transform valid Identifiers (`esutils.keyword.isIdentifierNameES5`) and not care about property names ?

**Comment by mathiasbynens** [comment]
There’s no `isPropertyName*` API in esutils (yet). I wonder how @Constellation and @michaelficarra feel about potentially adding it.

**Comment by michaelficarra** [comment]
@mathiasbynens Are you thinking of something like this? https://github.com/shapesecurity/shift-codegen-js/blob/0d09bd8a881c62c1bb85d6ff3cfa09697867ed0a/src/minimal-codegen.js#L636-L643

**Comment by mathiasbynens** [comment]
@michaelficarra Exactly!

**Comment by boopathi** [comment]
@michaelficarra Thanks a lot. I used the code from that repository and have also added the license. Please review the changes.

**Pull request merged**
