### PR TITLE
minify-dead-code-elimination: remove dead logical expressions

### PR DESCRIPTION
**Pull request by christophehurpeau**
Transforms:

```js
false && foo();
true && bar();
```

into:

```js
false;
bar();
```

### CODE REVIEW

**Comment by christophehurpeau** [comment]
@boopathi do you have something in mind ? How big ?

**Comment by boopathi** [comment]
+ Logical expr as a part of other expr like fn call,
+ expr with falsy & truthy values (not just true and false) - like '' || foo ...

**Comment by boopathi** [comment]
How different is this from this code in minify-guarded-expressions - https://github.com/babel/babili/blob/master/packages/babel-plugin-minify-guarded-expressions/src/index.js#L14-L51 Doesn't minify-guarded-expressions already take care of this optimization.

**Comment by christophehurpeau** [comment]
@boopathi okay thanks ! Did not saw it.

**Pull request closed without merging**
