### PR TITLE
Add link to repl [skip ci]

### PR DESCRIPTION
**Pull request by boopathi**

### CODE REVIEW

**Comment by kangax** [comment]
Would be nice to be able to toggle separate plugins too.

**Comment by boopathi** [comment]
We can enable passing in preset options once we get that ready ... maybe ?

**Comment by kangax** [comment]
I mean in the UI it would be nice to be able to toggle them, similar to how you can toggle other presets right now.

**Comment by hzoo** [comment]
Yeah would require some work. If we have that + umd plugins from npm we could debug more easily

**Pull request merged**
